export const personalInfo = {
  name: "Brandon Jose Tenorio Noguera",
  location: "DMV-Baltimore area, U.S.A.",
  email: "bjtn_website@bjtn.me",
  github: "https://github.com/bjtn1",
  linkedin: "https://www.linkedin.com/in/brandon-jose-tenorio-noguera/",
};

export const workExperience = [
  {
    company: "Teamania",
    location: "Rockville, MD",
    position: "Supervisor",
    period: "March 2019 - Present",
    achievements: [
      "- Led a team of 5 to optimize closing procedures, cutting down closing time by 25% through workflow restructuring.",
      "- Maintained and built relationships with 50+ customers daily",
      "- Provided exceptional customer service and efficient product deliveries",
      "- Ensured utmost customer satisfaction which resulted in an increase in tips by 100%",
      "- Demonstrated strong organizational skills in managing multiple tasks efficiently in a fast-paced environment",
      "- Managed and trained a team of 5 people to carry out efficient, effective, and satisfactory customer service resulting in reviews averaging a 4-star rating on sites like Yelp and Google reviews",
    ],
  },
  {
    company: "Biology Department of the University of Maryland - Baltimore County",
    location: "Catonsville, MD",
    position: "Research Lab Aide",
    period: "August 2023 - December 2023",
    achievements: [
      "- Collaborated closely with 6 graduate students to understand research needs and provide effective support",
      "- Safely handled and managed dangerous chemicals within a research laboratory environment",
      "- Thoroughly maintained a clean workspace with equipment in accordance to laboratory standards to prevent contamination",
    ],
  },
];

export const education = [
  {
    institution: "University of Maryland - Baltimore County",
    location: "Maryland, U.S.A.",
    degree: "Bachelor of Science in Computer Science",
    period: "May 2022 - December 2024",
    achievements: [
      "- CMSC 304: Social & Ethical Issues in Information Technology",
      "- CMSC 421: Principles of Operating Systems",
      "- CMSC 491: Special Topics in Computer Science - Social and Crowd Computing",
      "- CMSC 441: Design & Analysis of Algorithms",
      "- CMSC 447: Software Engineering I",
      "- CMSC 471: Artificial Intelligence",
      "- CMSC 478: Introduction to Machine Learning",
      "- STAT 355: Probability & Statistics for Science & Engineering",
      "- CMSC 426: Principles of Computer Security",
      "- MATH 221: Introduction to Linear Algebra",
      "- CMSC 341: Data Structures",
      "- CMSC 340: Advanced C++",
      "- CMSC 331: Principles of Programming Languages",
      "- CMSC 313: Compute Organization & Assembly Programming",
      "- CMSC 411: Computer Architecture",
      "- CMSC 449: Malware Analysis",
      "- BIOL 142: Foundations of Biology",
      "- SOCY 101: Basic Concepts in Sociology",
    ],
  },
  {
    institution: "Montgomery College",
    location: "Maryland, U.S.A.",
    degree: "Associate of Arts in Computer Science",
    period: "August 2018 - May 2022",
    achievements: [
      "- CMSC 140: Introduction to Programming",
      "- MATH 181: Calculus I",
      "- MATH 182: Calculus II",
      "- MATH 280: Multivariable Calculus",
      "- CMSC 140: Introduction to Programming",
      "- CMSC 203: Computer Science I",
      "- CMSC 204: Computer Science II",
      "- CMSC 207: Introduction to Discrete Structures",
    ],
  },
];
export const skills = {
  programmingAndDevelopment: [
    "Python",
    "Java",
    "C",
    "C++",
    "Rust",
    "JavaScript",
    "Lua",
    "PHP",
    "Bash",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Astro",
    "Git",
    "GitHub",
    "Neovim",
    "LaTeX",
    "ArcGIS",
    "Vim",
    "Kernel Development (Linux Syscalls)",
    "Scikit-learn",
    "Support Vector Machine (SVM)",
    "Google Calendar API",
    "OAuth 2.0",
    "Selenium",
    "BeautifulSoup",
  ],
  operatingSystems: [
    "Arch Linux",
    "EndeavourOS",
    "Kali Linux",
    "Debian",
    "Ubuntu",
    "macOS",
    "Windows 10/11",
  ],
  productivityAndOffice: [
    "Excel",
    "Google Sheets",
    "Microsoft Word",
    "Google Docs",
    "PowerPoint",
    "Google Slides",
  ],
  languages: [
    "Spanish (native)",
    "English (fluent)",
    "French (basic)",
    "ASL (basic)",
  ]
};

export const projects = [
  {
    title: "Net Zero Carbon Emissions",
    github: "https://github.com/rishikesh2003/Prodigi",
    demoUrl: "https://bjtn.me",
    description: [
      "WiFi-RTT: Developed indoor occupancy tracking for energy optimization.",
      "IoT Solutions: Implemented smart monitoring for energy efficiency and food waste reduction.",
      "Real-Time Tracking: Designed systems to monitor carbon emissions and optimize resources.",
      "Data-Driven Insights: Analyzed user patterns for adaptive energy and food management.",
      "Reward Integration: Built QR-based green points system to incentivize eco-friendly actions.",
    ],
  },
  {
    title: "Mental Aarog",
    github: "https://github.com/rishikesh2003/mental-aarog",
    description: [
      "A holistic mental health app leveraging AI and blockchain for early detection and personalized solutions for depression.",
      "Features include social media analysis (ML-based sentiment tracking), PHQ-9 assessments, smartwatch integration for sleep and activity data, guided meditation, and smart suggestions for food, travel, music, and movies.",
      "Developed a rewards system using MAG crypto token on Ethereum, enabling user engagement through in-app incentives.",
      "Secure storage implemented via web3.storage, IPFS, and FileCoin.",
      "Built with React, Supabase, Node.js, Flask, and Solidity, showcasing seamless integration of health tech and blockchain.",
    ],
  },
  {
    title: "Mental Aarog",
    github: "https://github.com/rishikesh2003/mental-aarog",
    description: [
      "A holistic mental health app leveraging AI and blockchain for early detection and personalized solutions for depression.",
      "Features include social media analysis (ML-based sentiment tracking), PHQ-9 assessments, smartwatch integration for sleep and activity data, guided meditation, and smart suggestions for food, travel, music, and movies.",
      "Developed a rewards system using MAG crypto token on Ethereum, enabling user engagement through in-app incentives.",
      "Secure storage implemented via web3.storage, IPFS, and FileCoin.",
      "Built with React, Supabase, Node.js, Flask, and Solidity, showcasing seamless integration of health tech and blockchain.",
    ],
  },
  {
    title: "Mental Aarog",
    github: "https://github.com/rishikesh2003/mental-aarog",
    description: [
      "A holistic mental health app leveraging AI and blockchain for early detection and personalized solutions for depression.",
      "Features include social media analysis (ML-based sentiment tracking), PHQ-9 assessments, smartwatch integration for sleep and activity data, guided meditation, and smart suggestions for food, travel, music, and movies.",
      "Developed a rewards system using MAG crypto token on Ethereum, enabling user engagement through in-app incentives.",
      "Secure storage implemented via web3.storage, IPFS, and FileCoin.",
      "Built with React, Supabase, Node.js, Flask, and Solidity, showcasing seamless integration of health tech and blockchain.",
    ],
  },
];

// export const awards = [
//   {
//     name: "IEEE YESIST12 Hackathon",
//     issuer: "IEEE",
//     date: "Sep 2022",
//     type: "International",
//     position: "Second Place",
//   },
//   {
//     name: "Prodigi Cognizant Hackathon",
//     issuer: "Cognizant",
//     date: "Feb 2023",
//     type: "National",
//     position: "Second Runner-up",
//   },
//   {
//     name: "Cisco Thingqbator Hackathon",
//     issuer: "Cisco",
//     date: "Jan 2023",
//     type: "National",
//     position: "First Runner-up",
//   },
//   {
//     name: "Innovators Day",
//     issuer: "Sri Manakula Vinayagar Engineering College, Pondicherry",
//     date: "Sep 2022",
//     type: "National",
//     position: "First Prize",
//   },
//   {
//     name: "KG Hackfest'22",
//     issuer: "KGiSL Institute of Technology, Coimbatore",
//     date: "Sep 2022",
//     type: "National",
//     position: "Second Prize",
//   },
//   {
//     name: "Innohacks'22",
//     issuer: "Innogeeks, KIET Group of Institutions, New Delhi",
//     date: "May 2022",
//     type: "National",
//     position: "Second Runner-up",
//   },
//   {
//     name: "Hack @ SKCET",
//     issuer: "Hackclub SKCET, SKCET, Coimbatore",
//     date: "Feb 2022",
//     type: "National",
//     position: "Most Impactful Hack",
//   },
// ];
